### PR TITLE
Simple kitematic cfg support for VM

### PR DESCRIPTION
**Pull request by FrenchBen**
This is a quick mod to allow 'advance' users to point Kitematic to their VM and if the VM doesn't exist, create it with the optional memory size.

Filename and location: `~/.kitematicfg`

Expected format:
```json
{
    "virtualbox": {
        "name": "default",
        "memory": "2048"
    }
}
```

Signed-off-by: FrenchBen <me(at)frenchben.com>

### CODE REVIEW

**Comment by FrenchBen** [comment]
@mchiang0610 @jeffdm Could you QA this change and see if it's applicable to the project?

Thanks!

**Comment by jeffdm** [comment]
@FrenchBen sorry for the delay. Thanks for the PR! My initial feeling is that we shouldn't introduce a new config file. Most users will probably create their VM before seeing this feature - meaning they need to delete their VM and re-create it for this to work.

**Comment by FrenchBen** [comment]
agreed - I did make some changes to it to be more of a VM selector in another PR

**Comment by bwidmeier** [comment]
I would just like to voice my support for this feature. I agree that it has limited discoverability, and even that users may discover it after beginning to build out the 'default' machine, but given that this is more targeted at advanced users anyways, I'm not sure that that matters too much. If a user wants to go through that process, why stop them?

I should note that actually integrating multi machine support into the UI would be a better option, but this config file option seems easy to do and helpful in the meantime.

**Comment by FrenchBen** [comment]
@bwidmeier I'm working on adding proper machine support into the UI, which prevents the need for this conf file :)

**Comment by bwidmeier** [comment]
@FrenchBen Thanks a lot! Is there an issue that I could subscribe to?

**Comment by FrenchBen** [comment]
@bwidmeier Checkout https://github.com/kitematic/kitematic/issues/1061

**Pull request closed without merging**
