### PR TITLE
Add support for advance VM config

### PR DESCRIPTION
**Pull request by FrenchBen**
This adds support for different driver and VM names, allowing a more 'advanced' user to select their VM and driver of choice. (as supported by docker-machine)

The config file is expected to be in the user's home directory and labelled `.kitematicfg`
The structure of the file is as follow:
```json
{
    "driver": "vmwarefusion",
    "name": "docker-vm"
}
```

Signed-off-by: FrenchBen

### CODE REVIEW

**Comment by michaeljs1990** [comment]
I need this very badly. I Run multiple docker-machines and i can't use kitematic right now at all unfortunately as it just keeps starting up my default machine.

**Comment by FrenchBen** [comment]
#closing in hopes of getting a more integrated solution in place where we can select the driver+vm from the GUI instead of a conf file

**Comment by michaeljs1990** [comment]
sounds like a good plan to me, any current open PRs for that or is it still in the works?

**Comment by FrenchBen** [comment]
@michaeljs1990 still in the works - I'll try to work on something this week and get some QA behind it. I'll mention you on the PR if you'd like?

**Comment by michaeljs1990** [comment]
that would be awesome, thank you.

**Comment by orefalo** [comment]
+1 on this one

**Comment by kpashka** [comment]
+1

**Comment by dvapelnik** [comment]
+1

**Pull request closed without merging**
