### PR TITLE
Flux links settings

### PR DESCRIPTION
**Pull request by TeckniX**
Containers can now be linked together!

Example:
- Create Hello-world-nginx container
- Create MariaDB container and update env setting for MYSQL_ROOT_PASSWORD to start the container
- Link hello-world-nginx to mariaDB via the links settings.
- Login to the hellow-world-nginx container and confirm env settings, which should be something like:

```bash
/# env
MARIADB_PORT=tcp://172.17.0.3:3306
MARIADB_PORT_3306_TCP=tcp://172.17.0.3:3306
HOSTNAME=1e54cecd0c2f
SHLVL=1
HOME=/root
MARIADB_NAME=/hello-world-nginx/mariadb
MARIADB_ENV_MARIADB_VERSION=10.0.19+maria-1~wheezy
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MARIADB_PORT_3306_TCP_ADDR=172.17.0.3
MARIADB_ENV_MYSQL_ROOT_PASSWORD=mariaaa
PWD=/
MARIADB_PORT_3306_TCP_PORT=3306
MARIADB_PORT_3306_TCP_PROTO=tcp
MARIADB_ENV_MARIADB_MAJOR=10.0
```

### CODE REVIEW

**Comment by jeffdm** [comment]
Great! Taking a look! Thanks @TeckniX

**Comment by TeckniX** [comment]
All updated - let me know if anything seems out of place

**Comment by jeffdm** [comment]
Taking another look - sorry for the delay since June.

**Comment by FrenchBen** [comment]
The code probably needs another update, since a few things were changes since then

**Comment by caiofbpa** [comment]
Is there any chance Kinematic automatically reads linking configuration from `docker-compose.yml` somewhere?

**Comment by FrenchBen** [comment]
@caiofbpa If the link was created via command line, Kitematic should pick it up too - The issue however is that if any changes are made to the container within Kitematic, there's a good chance that link will disappear. 
Reading docker-compose YML files is on the 'Future' list :)

**Comment by nVitius** [comment]
@jeffdm I just tested this locally after merging in master; it still works and the tests pass. Any updates on getting this merged in?

**Comment by FrenchBen** [comment]
@nVitius Thanks for checking the branch and confirming that it works as expected :+1:  - I just merged the latest master into this.

**Comment by nVitius** [comment]
The type-ahead probably shouldn't show the current container as an option. Though, if @TeckniX isn't working on this anymore, it's something that could be added after (if?) this is merged.

**Comment by FrenchBen** [comment]
@nVitius Good catch, I didn't think about typing in the current container name, as it seems that the user would understand that this isn't correct. I've got access to the repo and will make the adjustments next week.

Thanks!

**Comment by uatec** [comment]
@FrenchBen So did you get a chance to make those changes?

**Comment by FrenchBen** [comment]
@uatec It's on my list - I've been traveling and didn't get a chance to do anything with it. Thanks for the reminder :+1:

**Comment by FrenchBen** [comment]
Closing this in favor of networking introduced in 1.9

**Pull request closed without merging**
