### PR TITLE
Added preference for private repo url

### PR DESCRIPTION
**Pull request by FrenchBen**
Added support for private repo preference - Since I don't have one, I'll probably need some qa. 
There are still items that are linking to the v1 repo, which will need to be update, as previously seen in the paging functionality. 

Signed-off-by: FrenchBen <me(at)frenchben.com>

### CODE REVIEW

**Comment by FrenchBen** [comment]
v1 repo search has been removed in favor of the newer v2.

**Comment by jeffdm** [comment]
Thanks for the PR! I'm not sure if I understand who else implements this v2 api, therefore if anyone would need to change this setting.

**Comment by FrenchBen** [comment]
Screenshot of the repo preference:

private-repo

**Comment by FrenchBen** [comment]
#closing for not being applicable at the moment

**Pull request closed without merging**
