### PR TITLE
Updated support for port edit and improved exposed ports shown

### PR DESCRIPTION
**Pull request by FrenchBen**
All of this was based on the great work by @VojtechBartos but it's been updated to match the current code base with the addition of Getting exposed ports and previously set port settings.

Signed-off-by: FrenchBen <me(at)frenchben.com>

### CODE REVIEW

**Comment by rwatts3** [comment]
Nice this is the icing on the cake.  I've been waiting for this feature.

**Comment by FrenchBen** [comment]
@rwatts3 Do you mind taking it for a test drive and confirming that it works as expected?

**Comment by rwatts3** [comment]
Id be happy to do so.  I'm not sure on how to pull the pr and build for
testing could you iterate the steps here and I'd be happy to provide the
feedback.

On Thursday, August 20, 2015, FrenchBen <notifications@github.com> wrote:

> @rwatts3 <https://github.com/rwatts3> Do you mind taking it for a test
> drive and confirming that it works as expected?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kitematic/kitematic/pull/962#issuecomment-133099850>.
>


-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts

**Comment by FrenchBen** [comment]
Sure- this assumes you have nodejs/npm installed.

```bash
git clone -b port-edit https://github.com/FrenchBen/kitematic.git
cd kitematic
npm install
npm start
```
You should see the kitematic window open up and you can play with the different port settings.

**Comment by rwatts3** [comment]
Very well testing now.

**Comment by rwatts3** [comment]
Hmm running npm start returns errors is there something I need to do with
grunt first.

**Comment by siremurray** [comment]
@rwatts3 
Did you try running the npm commands with sudo?

**Comment by rwatts3** [comment]
Hi I'm actually on my work comp which has Windows I'm going to test tonight
on my Mac.

On Thursday, August 20, 2015, siremurray <notifications@github.com> wrote:

> @rwatts3 <https://github.com/rwatts3>
> Did you try running the npm commands with sudo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kitematic/kitematic/pull/962#issuecomment-133170582>.
>


-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts

**Comment by siremurray** [comment]
This is great. When does it get merged in?

**Comment by FrenchBen** [comment]
@siremurray Just need the team to look at it and give a thumbs up before it can be merged.

**Comment by andreysaksonov** [comment]
sorry, I didn't tracked all history of these PRs related to "port editing". is this PR will allow to persist assigned port for container (currently, Kitematic sequentially increase it on every start using 32768 as start point)?

**Comment by FrenchBen** [comment]
@andreysaksonov That's correct, the intent is to get the port editing to match your manual setup. A minimal check will be in place to prevent conflicts with ports, but it allows you to over-write the sequential port Kitematic uses

**Comment by jeffdm** [comment]
LGTM. Merging! This is a great change!

**Comment by FrenchBen** [comment]
:+1: :+1:  Thanks @jeffdm it was pretty high on the request list!

**Pull request merged**
