### PR TITLE
Linux electron prebuilt fix

### PR DESCRIPTION
**Pull request by timfallmk**
Added a switch case for getting the `electron-prebuilt` binary for linux.

### CODE REVIEW

**Comment by FrenchBen** [comment]
@timfallmk Can you check why a lot of the Travis CI are failing and get those to pass?

**Comment by jhirbour** [comment]
Probably related: https://www.traviscistatus.com/

**Comment by timfallmk** [comment]
```
 FAIL  __tests__/Util-test.js (0.698s)
● Util › when removing sensitive data › it filters Windows username data
  - Expected: 11 toEqual: -1
        at Spec.<anonymous> (/home/travis/build/kitematic/kitematic/__tests__/Util-test.js:35:75)
        at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
  - Expected: -1 toNotEqual: -1
        at Spec.<anonymous> (/home/travis/build/kitematic/kitematic/__tests__/Util-test.js:36:72)
        at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
```

Seems unrelated. I'll wait until Travis is feeling better and retrigger.

**Comment by timfallmk** [comment]
_Close/reopen to retrigger build_

**Comment by timfallmk** [comment]
Seems like the failed checks are unrelated to my changes? Could someone confirm that this is due to merged stuff from #696 ?

**Comment by jeffdm** [comment]
Thanks for this! Awesome! This indeed needs, to be caused by stuff in the linux PR. Will come back once that's merged. Thanks!

**Comment by FrenchBen** [comment]
Thanks @timfallmk for all the work on this - I will be closing this in favor of #696 as it's the most used PR as of now

**Pull request closed without merging**
