### PR TITLE
Update index.md

### LINKED ISSUE #921: https://docs.docker.com/kitematic/ has links pointing to localhost
Not sure where they should be pointing to but it probably isn't that

### PR DESCRIPTION
**Pull request by moxiegirl**
Removing a go template checked in by mistake.

Fixes #921

Signed-off-by: Mary Anthony <mary@docker.com>

### CODE REVIEW

**Comment by moxiegirl** [comment]
@thaJeztah

**Comment by thaJeztah** [comment]
LGTM

ping @jeffdm for the merge :)

**Comment by jeffdm** [comment]
Thanks, sorry for the delay in merging.

**Comment by thaJeztah** [comment]
@jeffdm 4 minutes? I've seen worse :smile:

Thanks!

**Pull request merged**
