### PR TITLE
Fixing problem reported by Sabine

### PR DESCRIPTION
**Pull request by moxiegirl**
Link to machine fix it!
Fixes: https://github.com/docker/docker/issues/15870

Signed-off-by: Mary Anthony <mary@docker.com>

cc: @mchiang0610 @jeffdm @theJetzah

### CODE REVIEW

**Comment by moxiegirl** [comment]
author LGTM

**Comment by mchiang0610** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM, thanks!

**Comment by jeffdm** [comment]
Thanks!

**Pull request merged**
