### PR TITLE
replace PID-0 with main container process, and tweak a little

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@fredlf @moxiegirl

**Comment by SvenDowideit** [comment]
I guess we'll get a fuller review when I push these docs to the docker/docker repo.

**Comment by jeffdm** [comment]
Great! LGTM on my side. Thanks Sven!

**Comment by SvenDowideit** [comment]
mmm, @jeffdm if you merge it today, I'll make a docker/docker repo merge PR later today too - so we can get that process underway

**Pull request merged**
