### PR TITLE
Modify OS list

### PR DESCRIPTION
**Pull request by ninuxio**

### CODE REVIEW

**Comment by jeffdm** [comment]
Thanks!

Not quite windows-ready yet but it's getting there fast thanks to @domderen's work!

**Comment by ninuxio** [comment]
yep awesome work !

**Comment by jeffdm** [comment]
Maybe  `Windows (coming soon)`? :stuck_out_tongue_winking_eye:

**Comment by ninuxio** [comment]
deal :D

**Comment by jeffdm** [comment]
Awesome!!! Merging :tada:

**Comment by jeffdm** [comment]
Thanks @ninuxio !

**Comment by jeffdm** [comment]
Oops didn't realize this was being merged into windows. Coming Soon not important after all :)

**Comment by ninuxio** [comment]
so we let like this ?

**Comment by ninuxio** [comment]
or win coming soon on master ?

**Comment by ninuxio** [comment]
@jeffdm we leave this in state ?

**Comment by jeffdm** [comment]
Will put it up on master too :) sorry for the delay in getting back!

**Comment by ninuxio** [comment]
ok you want another Pull request ?

**Comment by jeffdm** [comment]
It's okay, I just quick-edited on master via GitHub. Thanks @ninuxio :smile:

**Pull request merged**
