### PR TITLE
Change Windows paths and exec methods to allow mounting, ssh and terminal.

### PR DESCRIPTION
**Pull request by kraynel**

### CODE REVIEW

**Comment by jeffdm** [comment]
Fantastic! This is great. Thanks for the PR. Looking now.

In the meantime, can you [sign your commits](https://github.com/docker/docker/blob/master/CONTRIBUTING.md#sign-your-work)?

**Comment by kraynel** [comment]
Hi ! 
I squashed and amended the commits with the signature. Should be good now !

**Comment by jeffdm** [comment]
Great! Thanks @kraynel. Merging

**Comment by jeffdm** [comment]
Can't auto merge, can you merge in the `windows` branch? Looking great otherwise!

**Pull request merged**
