### PR TITLE
Added support for editing ports

### PR DESCRIPTION
**Pull request by VojtechBartos**
- little bit refactored ports component, removed not used code
- removed not necessary `display` field in response object
- tweaked style for input at ports component

Let me know if you have any questions
Vojta ;)

Signed-off-by: Vojta Bartos <hi@vojtech.me>

### CODE REVIEW

**Comment by jeffdm** [comment]
Awesome! Thanks for the PR.

Code LGTM

@mchiang0610 can you LGTM functionality?

**Comment by mchiang0610** [comment]
@VojtechBartos Thanks for the PR! This is an awesome feature. 

We'd need some error checking for the port numbers before we can merge.

**Comment by VojtechBartos** [comment]
@mchiang0610 yeah, will do that. Do you have any standardised way how to show errors to user ?

**Comment by VojtechBartos** [comment]
@mchiang0610 added all validation what you have suggested. Error message is gonna show on right side from port input. Hopefully is it ok. cc @jeffdm

**Comment by jeffdm** [comment]
Code LGTM

**Comment by mchiang0610** [comment]
@VojtechBartos  Can we not allow - ports 22 and 2376 ?  These are the ports that Kitematic / Docker uses.  

LGTM otherwise. :)

**Comment by VojtechBartos** [comment]
@mchiang0610 sure, done :)

**Comment by mchiang0610** [comment]
@VojtechBartos Thanks! Just one more bug that I noticed: 

The port is correctly mapped when I checked via command line but it's not showing up in Kitematic. 

image

**Comment by VojtechBartos** [comment]
@mchiang0610 Hey, i have merged current master, so check it out styling and etc.

About the bug, i haven't been able to replicate it. Have tried download some images what is in Recommended page. It works. Also have tried create new container from command line and map only one of three ports

`docker run -it -p 8080:80 vojtechbartos/dev`

Rest of the ports has not been mapped, but in Kitematic you could easily override it.

[Screenshot](https://www.dropbox.com/s/2clver60h7a88ea/kitematic.png?dl=0)

Can you give me more info about bug, please ? ;)

**Comment by VojtechBartos** [comment]
Hey @mchiang0610, any updates ? :)

**Comment by mchiang0610** [comment]
@VojtechBartos It works. Do you think we should block common ports from being used? For example if you try the hello-world-nginx image from Kitematic, and change to port 123 (NTP), it would just not run. 

(ie. https://technet.microsoft.com/en-us/library/cc959828.aspx)

**Comment by gpapin** [comment]
In my opinion, blocking common port is not a good idea as you could have a use case for having a docker image using it. What would be useful thought is a warning saying that the port selected is known as a common port (or already used by the system) and may cause conflicts.

**Comment by VojtechBartos** [comment]
@mchiang0610 sorry for my late response. I agree with @gpapin, we should not block it but just show up some warning on same place where is normally error message. I will do that but it is not gonna be in next couple days, because my schedule is pretty full at the moment. Question is, can you release it without it and i can create another separate PR later or you want to rather wait ?

**Comment by nateswart** [comment]
I've been using this PR for a few days and can say I'm loving the functionality. I'd vote for releasing it and, as you mention, subsequently create an additional feature enhancement to add additional messaging.

**Comment by TeckniX** [comment]
I merged this with Master and did a little bit of QA along with container linking - LGTM :+1:

**Comment by jeffdm** [comment]
@TeckniX great review. Yeah this seems like an outside error.

Taking another quick look at the code. Sorry for the long delay on getting this merged, @VojtechBartos.

**Comment by louy** [comment]
Any updates?

**Comment by FrenchBen** [comment]
@louy It seems the branch has a few conflicts that need to be resolved along with enhancements to make it work as expected -

**Comment by VojtechBartos** [comment]
@louy @FrenchBen sorry guys, my schedule was pretty full last couple weeks. I hope i will have free time to finish it during weekend.

**Comment by FrenchBen** [comment]
:+1: Thanks @VojtechBartos

**Comment by Quetzacoalt91** [comment]
This will be a great feature @VojtechBartos, thanks ! :+1:

**Comment by rwatts3** [comment]
Any idea on when this will be merged ?

**Comment by mchiang0610** [comment]
@rwatts3 Reviewing this asap, but it depends on if there is more work required for that PR to be merged.

**Comment by FrenchBen** [comment]
As seen above there are currently conflicts that @VojtechBartos will be updating - Currently he is unable to do so.
@rwatts3 Feel free to fork his Ports edit and make the necessary changes so that it can be merged :)

**Comment by FrenchBen** [comment]
Grabbed all relevant code to get everything up to date and tweaked a few things, as seen here:
https://github.com/kitematic/kitematic/pull/962

#close

**Comment by jeffdm** [comment]
Closing for #962

@VojtechBartos @FrenchBen huge thanks for your work on this, and apologies on the delay in getting it merged. Glad to see it come together. I'll make sure to give credit where it's due in the release notes.

**Comment by VojtechBartos** [comment]
Sorry guys that i have drop ball on this. I am currently finishing my master thesis and it takes a lot of time. But i am happy that this feature is finally in !

**Comment by FrenchBen** [comment]
@VojtechBartos No problem, thanks for doing the heavy lifting on it - Looks good!

**Pull request closed without merging**
