### PR TITLE
Updating Windows Branch with latest changes

### PR DESCRIPTION
**Pull request by jeffdm**

### CODE REVIEW

**Comment by jeffdm** [comment]
I'll just merge this if it's okay @domderen since it's just upstream changes (and a little fix to change UID to be a number instead of a string in SetupUtil)

**Comment by domderen** [comment]
Yeah all looks good. Does that add/remove any points from the windows client list?

**Comment by jeffdm** [comment]
Just the point where these changes work on Mac as well (pretty much worked out of the box).

**Comment by jeffdm** [comment]
Thanks for looking @domderen :)

**Pull request merged**
