### PR TITLE
Fill empty spaces

### PR DESCRIPTION
**Pull request by saiberz**
I'm not sure if this space's intentionally left blank

### CODE REVIEW

**Comment by FrenchBen** [comment]
Thank you for the PR - The 'empty' space is actually a result of the window size, where 3 image boxes cannot fit and thus wrap around. 
If the window was slightly bigger, then it would allow for them to span across the entire window width. 

Unfortunately your fix wouldn't allow for more than 2 images to be displayed on 1 row, which could look very ugly on larger screens. Could you try to tweak it so that 2 images fit 100% but if more than 2 could fit, then you see more? (3, 4, etc)

**Comment by saiberz** [comment]
@FrenchBen how about this? 
screen shot 2015-10-28 at 18 01 02
screen shot 2015-10-28 at 18 02 41

It fits the full width and can wrap many elements

**Comment by FrenchBen** [comment]
Much better, but if there is only '1' container on a row, it is stretched to the entire width of the window.[recommended](https://cloud.githubusercontent.com/assets/3965324/10806865/bdb3251e-7d96-11e5-9fd9-bc7c31192831.png)

**Comment by FrenchBen** [comment]
Thanks for the PR - Closing this for now as there isn't a proper solution.

**Pull request closed without merging**
