### PR TITLE
Linux groundwork

### PR DESCRIPTION
**Pull request by moimael**
Allow to download dependencies and start kitematic under Linux using npm start.

ref #49

### CODE REVIEW

**Comment by mchiang0610** [comment]
Thanks! It does run now once you have Node 0.10 installed, and then running npm install, npm start. 

That being said, there is still some work for Kitematic to work on Linux. 

image

**Comment by moimael** [comment]
Yes I know but I stopped here because next steps are not the same as mac and windows. From what I read on the bug report, most users (including me) would prefer to have kitematic talking directly to Linux host docker and not use VirtualBox + Boot2Docker. Which mean skipping setup screen and different code path for Linux. Any pointers on how it should be done ?

In the meantime can we merge this ? It is a least a first step and can help other devs looking to improve Linux support.

**Comment by mchiang0610** [comment]
@moimael Thanks! I agree. Docker can run native on Linux, and it's unideal to run it in a VM. 

@jeffdm can you review the code when you have a chance?

**Comment by zedtux** [comment]
@moimael and @mchiang0610 when will this be merged in master ?

**Comment by moimael** [comment]
The merge has conflict now, it is related to the switch to Grunt. Btw why did kitematic switched to Grunt ?

**Comment by zedtux** [comment]
Ha, this explain why my linux portage is working anyway without your merge request. This would mean that since the project has switched to Grunt, your pull request is no more needed, right ?

**Comment by jeffdm** [comment]
Looking!

In the meantime, sorry for the fast switch to Grunt. Many of the electron and atom community tools are written in Grunt and to keep up we'd need to maintain gulp-rewritten forks.

**Comment by mickaelandrieu** [comment]
Hi, what is the status of this pull request, any chance to be merged ?

An ubuntu user who love good UI :)

**Comment by moimael** [comment]
@zedtux Any plan to merge your linux work ?

**Comment by zedtux** [comment]
My pull request is over here: https://github.com/kitematic/kitematic/pull/696.

**Comment by TeckniX** [comment]
@moimael Would you mind closing this PR in favor of @zedtux 's PR https://github.com/kitematic/kitematic/pull/696 ?

**Comment by moimael** [comment]
Not at all, his work seems much more advanced !

**Comment by TeckniX** [comment]
:+1:

**Pull request closed without merging**
