### PR TITLE
Add support for menu bar actions

### PR DESCRIPTION
**Pull request by FrenchBen**
A kitematic menubar is now present within the OSX menu, allowing a user to close the kitematic window and still have access to the containers created.

Menu Actions are:
* Settings (main container settings window)
* Start/Stop (depending on the current status)
* Restart

menubar

ps: the menu icon should be updated to a black & white color. 

Signed-off-by: FrenchBen <me(at)frenchben.com>

### CODE REVIEW

**Comment by timfallmk** [comment]
:100: . Make sure the icon supports low opacity. El Capitan will have an even more transparent menu bar during certain states.

**Comment by Elesant** [comment]
Haha nice. This is pretty cool!

**Comment by FrenchBen** [comment]
@Elesant Do you think you could provide an updated icon for this plz? :D

**Comment by FrenchBen** [comment]
Put on the back-burner for now

**Pull request closed without merging**
